version: '3.9'

services:
  api:
    build: ./MinMinBE
    env_file:
      - MinMinBE/.env
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
  customer-fe:
    build:
      context: ./MinMinFECustomer
      dockerfile: dockerfile
    ports:
      - '3000:3000'
  restaurant-fe:
    build:
      context: ./MinMinFERestaurant
      dockerfile: dockerfile
    ports:
      - '3001:3000'
  db:
    image: postgis/postgis
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  pgdata:
