# Generated by Django 5.1.3 on 2025-03-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
