# Generated by Django 5.1.3 on 2025-03-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('placed', 'Placed'), ('progress', 'Progress'), ('payment_complete', 'Payment Complete'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=30),
        ),
    ]
