# Generated by Django 5.1.3 on 2025-04-02 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_share_post_shares'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='share',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='post',
            name='shares',
        ),
        migrations.AddField(
            model_name='post',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='share',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='feed.post'),
        ),
        migrations.AlterField(
            model_name='share',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
