# Generated by Django 5.1.3 on 2025-06-13 09:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_gps_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
