# Stage 1: Build the Expo web app
FROM node:23-alpine AS builder

# Set working directory
WORKDIR /app

ENV EXPO_PUBLIC_API_URL=https://alpha.feed-intel.com/api/v1 \
    EXPO_PUBLIC_BACKEND_URL=https://alpha.feed-intel.com/api/ \
    EXPO_PUBLIC_IMAGE_PATH=https://alpha.feed-intel.com \
    EXPO_PUBLIC_API_KEY=oiWttKrw.oiWttKrw.aVjV9LaPZ7sxxJIB8gOj918lYPDugvbO \
    EXPO_PUBLIC_WS_URL=wss://alpha.feed-intel.com/ws/restaurant/

# Install dependencies
COPY package.json ./
RUN yarn install

# Install Expo CLI
RUN yarn global add expo-cli

# Copy the rest of the application
COPY . .

# Build the static web app
RUN npx expo export --platform web

CMD ["npx", "expo", "serve"]
