# Generated by Django 5.1.3 on 2025-02-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='TEMP-ORDER-ID', editable=False, max_length=50),
        ),
    ]
