# Generated by Django 5.1.3 on 2025-02-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('mobile_wallet', 'Mobile Wallet'), ('chapa', 'Chapa')], default='chapa', max_length=20),
        ),
    ]
