# Generated by Django 5.1.3 on 2025-03-01 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
        ('tenant', '0002_alter_tenant_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_customer_loyalty_transaction', to='tenant.tenant'),
        ),
    ]
