# Generated by Django 5.1.3 on 2025-03-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_alter_loyaltytransaction_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantloyaltysettings',
            old_name='global_points',
            new_name='threshold',
        ),
    ]
