# Generated by Django 5.1.3 on 2025-02-05 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related_menu', '0001_initial'),
        ('tenant', '0002_alter_tenant_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedmenuitem',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_related_menu_items', to='tenant.tenant'),
        ),
    ]
