# Generated by Django 5.1.3 on 2025-03-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_tenant_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='CHAPA_API_KEY',
            field=models.TextField(blank=True, null=True),
        ),
    ]
