# Generated by Django 5.1.3 on 2025-06-12 06:40

import restaurant.tenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_tenant_chapa_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=restaurant.tenant.models.user_image_path),
        ),
    ]
