# Generated by Django 5.1.3 on 2025-02-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountrule',
            name='applicable_items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='excluded_items',
            field=models.JSONField(default=list),
        ),
    ]
