# Generated by Django 5.1.3 on 2025-03-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_alter_discountrule_applicable_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountrule',
            name='max_items',
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='buy_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='combo_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='get_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='max_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='min_items',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
