# Generated by Django 5.1.3 on 2025-03-18 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_comment_feedback_menu_feedback_restaurant_and_more'),
        ('menu', '0002_alter_menu_image'),
        ('order', '0004_alter_order_status'),
        ('tenant', '0002_alter_tenant_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_feedback_per_order'),
        ),
    ]
