# Generated by Django 5.1.3 on 2025-01-01 06:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'coupons',
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_items', models.IntegerField()),
                ('max_items', models.IntegerField()),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applicable_items', models.JSONField()),
                ('excluded_items', models.JSONField()),
                ('combo_size', models.IntegerField()),
                ('buy_quantity', models.IntegerField()),
                ('get_quantity', models.IntegerField()),
                ('is_percentage', models.BooleanField(default=False)),
                ('max_discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'discount_rules',
                'db_table': 'discount_rule',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('volume', 'Volume'), ('combo', 'Combo'), ('bogo', 'BOGO'), ('freeItem', 'Free Item'), ('coupon', 'Coupon')], default='volume', max_length=255)),
                ('off_peak_hours', models.BooleanField(default=False)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('is_stackable', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_discounts', to='branch.branch')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_discounts', to='discount.coupon')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_discounts', to='tenant.tenant')),
            ],
            options={
                'verbose_name_plural': 'discounts',
                'db_table': 'discount',
            },
        ),
        migrations.CreateModel(
            name='DiscountApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_discount_applications', to='discount.discount')),
            ],
            options={
                'verbose_name_plural': 'discount_applications',
                'db_table': 'discount_application',
            },
        ),
    ]
