# Generated by Django 5.1.3 on 2025-01-01 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discount', '0001_initial'),
        ('order', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountapplication',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_discount_applications', to='order.order'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='discount_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_discount_rules', to='discount.discount'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_discount_rules', to='tenant.tenant'),
        ),
    ]
