# Generated by Django 5.1.3 on 2025-10-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('discount', '0002_couponusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='branch',
        ),
        migrations.AddField(
            model_name='coupon',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discount',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
