# Generated by Django 5.1.3 on 2025-12-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_remove_coupon_branch_remove_discount_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='is_global',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_global',
            field=models.BooleanField(default=True),
        ),
    ]
