# Generated by Django 5.1.3 on 2025-12-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_alter_coupon_is_global_alter_discount_is_global'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountrule',
            old_name='excluded_items',
            new_name='free_items',
        ),
    ]
