# Generated by Django 5.1.3 on 2025-04-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_coupon_discount_amount_coupon_is_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('volume', 'Volume'), ('combo', 'Combo'), ('bogo', 'BOGO'), ('freeItem', 'Free Item')], default='volume', max_length=255),
        ),
    ]
