# Generated by Django 5.1.3 on 2025-02-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_code',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
