# Generated by Django 5.1.3 on 2025-02-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20250227_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_code',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
