# Generated by Django 5.1.3 on 2025-03-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_alter_table_table_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_code',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
