# Generated by Django 5.1.3 on 2025-02-05 10:41

import restaurant.menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to=restaurant.menu.models.tenant_image_path),
        ),
    ]
