# Generated by Django 5.1.3 on 2025-09-18 08:15

from django.db import migrations, models


def forwards_copy_categories(apps, schema_editor):
    Menu = apps.get_model('menu', 'Menu')
    for menu in Menu.objects.all():
        legacy_value = getattr(menu, 'category', None)
        categories_value = getattr(menu, 'categories', None)

        # Preserve existing categories if already populated
        if isinstance(categories_value, list) and categories_value:
            continue

        if legacy_value is None:
            menu.categories = []
        elif isinstance(legacy_value, (list, tuple)):
            menu.categories = [str(item).strip() for item in legacy_value if str(item).strip()]
        else:
            legacy_str = str(legacy_value).strip()
            menu.categories = [legacy_str] if legacy_str else []

        menu.save(update_fields=['categories'])


def backwards_restore_category(apps, schema_editor):
    Menu = apps.get_model('menu', 'Menu')
    for menu in Menu.objects.all():
        categories_value = getattr(menu, 'categories', None)
        if isinstance(categories_value, list) and categories_value:
            menu.category = categories_value[0]
        else:
            menu.category = ''
        menu.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='categories',
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(forwards_copy_categories, backwards_restore_category),
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
    ]
