# Generated by Django 5.1.3 on 2025-01-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('restaurant', 'Restaurant'), ('branch', 'Branch'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
    ]
