# Generated by Django 5.1.3 on 2025-12-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tin_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
