# Generated by Django 5.1.3 on 2025-09-21 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedMenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(choices=[('Best Paired With', 'Best Paired With'), ('Alternative', 'Alternative'), ('Customer Favorite', 'Customer Favorite')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_menu_items', to='menu.menu')),
                ('related_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_items', to='menu.menu')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_related_menu_items', to='tenant.tenant')),
            ],
            options={
                'unique_together': {('menu_item', 'related_item', 'tenant')},
            },
        ),
    ]
