# Generated by Django 5.1.3 on 2025-10-09 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('related_menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedmenuitem',
            name='tag',
        ),
    ]
