# Generated by Django 5.1.3 on 2025-09-21 16:40

import django.db.models.deletion
import restaurant.tenant.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=restaurant.tenant.models.user_image_path)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('profile', models.TextField()),
                ('CHAPA_API_KEY', models.TextField(blank=True, null=True)),
                ('CHAPA_PUBLIC_KEY', models.TextField(blank=True, null=True)),
                ('tax', models.FloatField(default=0.0)),
                ('service_charge', models.FloatField(default=0.0)),
                ('max_discount_limit', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
