# Generated by Django 5.1.3 on 2025-04-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_tenant_chapa_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='service_charge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
    ]
