# Generated by Django 5.1.3 on 2025-05-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_tenant_service_charge_tenant_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='CHAPA_PUBLIC_KEY',
            field=models.TextField(blank=True, null=True),
        ),
    ]
