name: Deploy Restaurant Frontend

on:
  push:
    branches: [develop, main]
    paths:
      - 'restaurantFE/**'
      - '.github/workflows/deploy-fe-restaurant.yml'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: restaurantFE/package-lock.json

      - name: Install dependencies
        working-directory: restaurantFE
        run: npm ci

      - name: Build
        working-directory: restaurantFE
        run: npm run build

      - name: Archive build
        run: |
          cd restaurantFE && zip -r ../restaurantFE.zip dist

      - name: Deploy to Amplify
        uses: aws-amplify/amplify-hosting-deploy@v2
        with:
          app-id: ${{ secrets.AMPLIFY_APP_ID_RESTAURANT }}
          branch: ${{ vars.AMPLIFY_BRANCH }}
          artifact: restaurantFE.zip
