name: deploy-staging-fecustomer

on:
  push:
    branches: [develop]
    paths:
      - 'MinMinFECustomer/**'
      - '.github/workflows/deploy-fecustomer.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
        working-directory: MinMinFECustomer
      - run: npm run build
        working-directory: MinMinFECustomer
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-west-3
      - run: aws s3 sync dist/ "s3://${{ secrets.S3_FRONTEND_BUCKET }}/" --delete
        working-directory: MinMinFECustomer
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DIST_ID }} --paths "/*"
