name: Deploy Customer FE to Amplify

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/customer-fe/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Trigger Amplify build
        run: |
          BRANCH=$( [ "${GITHUB_REF##*/}" = "main" ] && echo "main" || echo "${{ secrets.AMPLIFY_BRANCH_CUSTOMER }}" )
          aws amplify start-job --app-id ${{ secrets.AMPLIFY_APP_ID_CUSTOMER }} --branch-name $BRANCH --job-type RELEASE
